site_name: Documentation GNN ArticleClassifier
site_url: https://GNNAC.com/

theme:
    name: readthedocs

nav:
    - Index: index.md
    - Setting up: project_installation.md
    - Configuring Settings: settings.md
    - Data Preparation: preparing_data.md
    - Training: training.md
    - Optimization: optimization.md








