site_name: Documentation GNN ArticleClassifier
repo_url: https://github.com/rvdb7345/ArticleClassifier
site_author: Robin van den Berg
site_url: https://github.com/rvdb7345/ArticleClassifier

theme:
    palette:
        primary: teal
    name: material
    logo: frontpagerounded.png
    favicon: seethroughthesislogo.png
plugins:
    - search
nav:
    - Welcome: index.md
    - Setting Up: project_installation.md
    - Configuring Settings: settings.md
    - Data Preparation: preparing_data.md
    - Training: training.md
    - Optimization: optimization.md








